version: 0.2
# tells CodeBuild how to build our application
phases:
  install:
    runtime-versions:
      nodejs: 10

  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
artifacts:
  files:
    - start-service-sh
    - stop-service.sh
    - server.js
    - package.json
    - appspec.yml
    - 'node_modules/**/*'