AWSTemplateFormatVersion: 2010-09-09

Paramters:
  CodePipelineBucket:
    Type: String
    Description: The S3 bucket for CodePipeline artifacts.

Resources:
  CodePipelineS3Bucket:
    Type: AWS::S3::bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref CodePipelineBucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256